apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supermarket-mcp-data
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 2Gi
